//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.13 at 10:03:08 AM CET 
//


package aka.jmetaagentsgenerator.xml.query;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the aka.jmetaagentsgenerator.xml.query package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: aka.jmetaagentsgenerator.xml.query
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link Query.Parameters }
     * 
     */
    public Query.Parameters createQueryParameters() {
        return new Query.Parameters();
    }

    /**
     * Create an instance of {@link Query.Parameters.UrlQuery }
     * 
     */
    public Query.Parameters.UrlQuery createQueryParametersUrlQuery() {
        return new Query.Parameters.UrlQuery();
    }

    /**
     * Create an instance of {@link Query.Parameters.Path }
     * 
     */
    public Query.Parameters.Path createQueryParametersPath() {
        return new Query.Parameters.Path();
    }

    /**
     * Create an instance of {@link Query.Parameters.Headers }
     * 
     */
    public Query.Parameters.Headers createQueryParametersHeaders() {
        return new Query.Parameters.Headers();
    }

    /**
     * Create an instance of {@link Query.Method }
     * 
     */
    public Query.Method createQueryMethod() {
        return new Query.Method();
    }

    /**
     * Create an instance of {@link Query.Parameters.UrlQuery.Parameter }
     * 
     */
    public Query.Parameters.UrlQuery.Parameter createQueryParametersUrlQueryParameter() {
        return new Query.Parameters.UrlQuery.Parameter();
    }

    /**
     * Create an instance of {@link Query.Parameters.Path.Parameter }
     * 
     */
    public Query.Parameters.Path.Parameter createQueryParametersPathParameter() {
        return new Query.Parameters.Path.Parameter();
    }

    /**
     * Create an instance of {@link Query.Parameters.Headers.Parameter }
     * 
     */
    public Query.Parameters.Headers.Parameter createQueryParametersHeadersParameter() {
        return new Query.Parameters.Headers.Parameter();
    }

}
